pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Status.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/StatusBurn.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/StatusFreeze.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/StatusParalysis.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/StatusPoison.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/StatusSleep.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/a.java

Added Status Conditions architecture

---

pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/PokemonController.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Pokemon.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/repository/PokemonRepository.java

Added basic shell for pokemon class and added in basic methods

---

pokemon-app/src/main/java/com/QA/pokemonapp/business/service/PokemonGeneratorService.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/Constants.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/EPokeball.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/EPotion.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/EStatus.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/ETerrain.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/ETypes.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/GetRandomFromEnum.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/TypeEffectivenessChecker.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/PokemonController.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/a.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Pokemon.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/items/ItemPotion.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/status/StatusFaint.java
pokemon-app/src/main/resources/Constants.java

Enum cover

---

pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/TypeEffectivenessChecker.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/TypeEffectivenessChart.java

(to be used with data from the api)

Added class which describes the damage relations between Pokemon Types

---

README.md
pokemon-app/src/main/java/com/QA/pokemonapp/PokemonAppApplication.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/PlayerPokemonService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/PokemonGeneratorInterface.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/PokemonGeneratorService.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/PokemonPokeAPIController.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/PokemonRestController.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Pokemon.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/repository/a.java

Pokemon rest

---

pokemon-app/src/main/java/com/QA/pokemonapp/business/service/BattleManager.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/EDamageClass.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Pokemon.java

Initial BattleManager

---

pokemon-app/src/main/java/com/QA/pokemonapp/business/service/ItemGeneratorInterface.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/ItemGeneratorService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/PlayerPokemonService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/ShopService.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/EPokeball.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/ItemAPIController.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/ShopRestcontroller.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Pokemon.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Shop.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/items/Item.java

Added service and rest layers for the item and shop class

---

pokemon-app/src/main/java/com/QA/pokemonapp/business/service/BattleManager.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/TypeEffectivenessChecker.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Move.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Player.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Pokemon.java

Added the Move Noun object

---

pokemon-app/src/main/java/com/QA/pokemonapp/PokemonAppApplication.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/PokemonGeneratorService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/terrain/TerrainGenerator.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/terrain/TerrainInterface.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/Constants.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/ETerrain.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/ETypes.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/PokemonRestController.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/terrain/TerrainPokeAPIController.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/terrain/TerrainRestController.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Move.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Terrain.java

Added a terrain generator with random pokemon encounters

---

pokemon-app/src/main/java/com/QA/pokemonapp/PokemonAppApplication.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/BattleManager.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/PlayerPokemonService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/PokemonGeneratorService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/ShopService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/move/MoveGeneratorService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/player/PlayerService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/type/Player.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/type/TypeEffectivenessInterface.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/type/TypeEffectivenessService.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/TypeEffectivenessChecker.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/battle/BattleRestController.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/terrain/TerrainRestController.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/type/TypeEffectivenessPokeAPIController.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/items/ItemPokeball.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/items/ItemPotion.java

Rest domain branch

---

pokemon-app/src/main/java/com/QA/pokemonapp/business/service/BattleManager.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/player/PlayerService.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/battle/BattleRestController.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/items/Item.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/items/ItemPokeball.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/items/ItemPotion.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/status/StatusBurn.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/status/StatusPoison.java

Fixed errors with status damage and item use

---

pokemon-app-react/src/App.css
pokemon-app-react/src/App.js
pokemon-app-react/src/Battle.js
pokemon-app-react/src/PokemonParty.js
pokemon-app-react/src/Roam.js
pokemon-app-react/src/StarterPokemon.js

React roam

---

pokemon-app-react/src/App.css
pokemon-app-react/src/BuyMenu.js
pokemon-app-react/src/SellMenu.js
pokemon-app-react/src/Shop.js
pokemon-app/src/main/java/com/QA/pokemonapp/PokemonAppApplication.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/item/ShopService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/player/PlayerService.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/item/ShopRestcontroller.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Player.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Shop.java

Shop branch

---

pokemon-app-react/src/App.js
pokemon-app-react/src/Battle.js
pokemon-app-react/src/Choose.js
pokemon-app-react/src/FightMenu.js
pokemon-app-react/src/Roam.js

Added the moves to the fight menu

---

pokemon-app/src/main/java/com/QA/pokemonapp/PokemonAppApplication.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/PlayerPokemonService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/PokemonGeneratorInterface.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/PokemonGeneratorService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/item/ItemService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/terrain/TerrainGenerator.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/item/ItemRestController.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/EnemyPokemon.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Terrain.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/items/Item.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/items/ItemPokeball.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/items/ItemPotion.java

Added item rest controller and EnemyPokemon class to allow easier method

---

pokemon-app-react/src/App.js
pokemon-app-react/src/Choose.js
pokemon-app-react/src/Roam.js
pokemon-app-react/src/StarterPokemon.js

Made some small changes

---

pokemon-app/src/main/java/com/QA/pokemonapp/business/service/BattleManager.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/PokemonGeneratorInterface.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/PokemonGeneratorService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/terrain/TerrainGenerator.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/EnemyPokemon.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/Terrain.java

added in correct flow for enemy pokemon generation and set to enemy

---

pokemon-app-react/src/App.css
pokemon-app-react/src/App.js
pokemon-app-react/src/Bag.js
pokemon-app-react/src/Battle.js
pokemon-app-react/src/MainGame.js
pokemon-app-react/src/PokemonParty.js
pokemon-app-react/src/Roam.js
pokemon-app-react/src/Shop.js

React updates

---

pokemon-app-react/src/StarterPokemon.js
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/PokemonPokeAPIController.java

changed rest layer to add pokemon to party

---

pokemon-app/src/main/java/com/QA/pokemonapp/business/service/BattleManager.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/PokemonGeneratorService.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/battle/BattleRestController.java
pokemon-app/src/main/java/com/QA/pokemonapp/persistance/domain/EnemyPokemon.java

Known bug: TakesNoDamage types still cause damage

Fixed more battle issues

---

pokemon-app-react/src/App.js
pokemon-app-react/src/Battle.js
pokemon-app-react/src/BuyMenu.js
pokemon-app-react/src/Choose.js
pokemon-app-react/src/FightMenu.js
pokemon-app-react/src/MainGame.js
pokemon-app-react/src/PokemonParty.js
pokemon-app-react/src/Roam.js
pokemon-app-react/src/SellMenu.js
pokemon-app-react/src/StarterPokemon.js

React battle integration 2

---

pokemon-app/src/main/java/com/QA/pokemonapp/business/service/item/ItemGeneratorService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/item/ItemService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/item/ShopService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/move/MoveGeneratorService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/player/PlayerService.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/terrain/TerrainGenerator.java
pokemon-app/src/main/java/com/QA/pokemonapp/business/service/type/TypeEffectivenessService.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/Constants.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/EDamageClass.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/EPokeball.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/EPotion.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/EStatus.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/ETerrain.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/ETypes.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/GetRandomFromEnum.java
pokemon-app/src/main/java/com/QA/pokemonapp/constantsandenums/TypeEffectivenessChecker.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/battle/BattleRestController.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/item/ItemAPIController.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/item/ItemRestController.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/item/ShopRestController.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/move/MovePokeAPIController.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/player/PlayerRestController.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/terrain/TerrainPokeAPIController.java
pokemon-app/src/main/java/com/QA/pokemonapp/interoperability/rest/type/TypeEffectivenessPokeAPIController.java

Java doc branch
